
[2023-12-12 16:35:40,571] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Reached accuracy 54.44% on epoch 1. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.01174
Epoch: 1/100	Train Loss: 1.7870	Test Loss: 1.2826	Accuracy: 54.44%	Current LR: 0.00025	Elapsed Time: 00:01:23	Expected Time: 02:18:56
Reached accuracy 55.79% on epoch 2. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.04785
Epoch: 2/100	Train Loss: 1.2142	Test Loss: 1.3137	Accuracy: 55.79%	Current LR: 0.00050	Elapsed Time: 00:02:03	Expected Time: 01:42:35
Reached accuracy 65.29% on epoch 3. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.09634
Epoch: 3/100	Train Loss: 0.9937	Test Loss: 1.0393	Accuracy: 65.29%	Current LR: 0.00075	Elapsed Time: 00:02:42	Expected Time: 01:30:29
Reached accuracy 70.17% on epoch 4. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.15142

Epoch: 5/100	Train Loss: 0.7489	Test Loss: 1.0788	Accuracy: 65.74%	Current LR: 0.00100	Elapsed Time: 00:04:17	Expected Time: 01:25:54
Reached accuracy 74.36% on epoch 6. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.25719
Epoch: 6/100	Train Loss: 0.6519	Test Loss: 0.7700	Accuracy: 74.36%	Current LR: 0.00100	Elapsed Time: 00:05:05	Expected Time: 01:24:47
Reached accuracy 79.85% on epoch 7. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.30226

Epoch: 8/100	Train Loss: 0.5409	Test Loss: 0.6501	Accuracy: 77.77%	Current LR: 0.00100	Elapsed Time: 00:06:41	Expected Time: 01:23:34
Reached accuracy 81.04% on epoch 9. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.37935


Epoch: 11/100	Train Loss: 0.4245	Test Loss: 0.6219	Accuracy: 79.62%	Current LR: 0.00099	Elapsed Time: 00:09:02	Expected Time: 01:22:11
Reached accuracy 83.85% on epoch 12. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.47244
Epoch: 12/100	Train Loss: 0.3990	Test Loss: 0.4742	Accuracy: 83.85%	Current LR: 0.00098	Elapsed Time: 00:09:43	Expected Time: 01:20:59
Reached accuracy 84.01% on epoch 13. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.49864

Epoch: 14/100	Train Loss: 0.3518	Test Loss: 0.4930	Accuracy: 83.86%	Current LR: 0.00097	Elapsed Time: 00:11:04	Expected Time: 01:19:09
Reached accuracy 85.64% on epoch 15. Model saved to /global/home/users/njo/PAdam/python/./CIFAR10/p0p8/best_model.pth.
Sparsity: 0.54464

Epoch: 16/100	Train Loss: 0.3148	Test Loss: 0.4333	Accuracy: 85.55%	Current LR: 0.00096	Elapsed Time: 00:12:27	Expected Time: 01:17:49
Exception ignored in: <function _releaseLock at 0x7f4332472430>
Traceback (most recent call last):
  File "/global/home/users/njo/anaconda3/lib/python3.8/logging/__init__.py", line 223, in _releaseLock
    def _releaseLock():

Epoch: 17/100	Train Loss: 0.2965	Test Loss: 0.4773	Accuracy: 85.17%	Current LR: 0.00096	Elapsed Time: 00:13:08	Expected Time: 01:17:16
Exception in thread Thread-39:
Traceback (most recent call last):
  File "/global/home/users/njo/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/global/home/users/njo/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "./python/train_CIFAR.py", line 322, in <module>
    main()
  File "./python/train_CIFAR.py", line 233, in main
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/nn/utils/clip_grad.py", line 76, in clip_grad_norm_
    torch._foreach_mul_(grads, clip_coef_clamped.to(device))  # type: ignore[call-overload]
KeyboardInterrupt